# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-31 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0003_auto_20171101_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
